# 01 — Deep-PK CYP substrate data audit

Put the five downloaded **substrate** CSV files in `data/raw/`, then run this notebook.
Inspect the real column names and label meanings before cleaning or modeling.

**Critical:** a missing measurement for an isoform is not a non-substrate label.

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in C:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy in C:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
files = sorted(RAW_DIR.glob("*.csv"))
print("Project root:", PROJECT_ROOT.resolve())
print("CSV files found:", len(files))
for f in files:
    print("-", f.name)

Project root: C:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability
CSV files found: 15
- cyp1a2_test.csv
- cyp1a2_train.csv
- cyp1a2_val.csv
- cyp2c19_test.csv
- cyp2c19_train.csv
- cyp2c19_val.csv
- cyp2c9_test.csv
- cyp2c9_train.csv
- cyp2c9_val.csv
- cyp2d6_test.csv
- cyp2d6_train.csv
- cyp2d6_val.csv
- cyp3a4_test.csv
- cyp3a4_train.csv
- cyp3a4_val.csv

In [3]:
datasets = {}
for f in files:
    try:
        df = pd.read_csv(f)
        datasets[f.name] = df
        print(f"\\n{'='*70}\\n{f.name}: {df.shape}")
        print("Columns:", df.columns.tolist())
        display(df.head())
    except Exception as e:
        print(f"Could not read {f.name}: {e}")

if not files:
    print("No CSVs found. Download the five substrate datasets from:")
    print("https://biosig.lab.uq.edu.au/deeppk/data/")
    print("Place the files in data/raw/ and rerun.")

\n======================================================================\ncyp1a2_test.csv: (37, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0                                         OCCOCCOCCO    0.0  test
1                               c1ccc([C@@H]2CO2)cc1    0.0  test
2                                 NC(CCSC(F)F)C(=O)O    0.0  test
3  CC(C)CCCCCCCCC(=O)N(C)C(CO)C(=O)NC(C)C(=O)NCC(...    0.0  test
4     OC[C@H]1O[C@@H](n2cnc3c2N=CNC[C@H]3O)C[C@@H]1O    0.0  test

\n======================================================================\ncyp1a2_train.csv: (292, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label     group
0  CC[C@H]1OC(=O)C(C)[C@@H](O[C@H]2C[C@@](C)(OC)[...    1.0  training
1        O=C(O)C(Cc1ccccc1)C(Cc1ccc2c(c1)OCO2)C(=O)O    0.0  training
2                O=C1CCC(N2C(=O)c3ccccc3C2=O)C(=O)N1    1.0  training
3                                 NCC1CCC(C(=O)O)CC1    0.0  training
4                 CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1    1.0  training

\n======================================================================\ncyp1a2_val.csv: (37, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0                       NCC(=O)Nc1ccc(OCc2ccccc2)cc1    0.0   val
1  CC(C)c1nc(CN(C)C(=O)NC(C(=O)N[C@@H](Cc2ccccc2)...    1.0   val
2  C=C[C@H]1CN2CC[C@H]1C[C@H]2[C@H](O)c1ccnc2ccc(...    1.0   val
3                              NCCC(=O)NCCC(N)C(=O)O    0.0   val
4     O[C@@H]1[C@H](O)Cc2c(ccc3ccc4ccccc4c23)[C@H]1O    0.0   val

\n======================================================================\ncyp2c19_test.csv: (26, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0               N=C(CCSCc1csc(N=C(N)N)n1)NS(N)(=O)=O    1.0  test
1  CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](...    0.0  test
2                                 NCC1CCC(C(=O)O)CC1    0.0  test
3  CC(=O)N[C@@H]1[C@@H]([C@@H](O)[C@H](O)CO)O[C@@...    0.0  test
4  CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...    0.0  test

\n======================================================================\ncyp2c19_train.csv: (208, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label     group
0  COc1ccc(F)c(F)c1C(=O)c1cnc(NC2CCN(S(C)(=O)=O)C...    0.0  training
1                      CCOC(=O)C1(c2ccccc2)CCN(C)CC1    1.0  training
2                         O=C(O)/C=C/c1ccc(B(O)O)cc1    0.0  training
3                          CCCc1cc(=O)[nH]c(=S)[nH]1    0.0  training
4    CC(C)(C)Nc1nc(C(F)(F)F)nc2ccc(-c3cccc(N)c3)cc12    0.0  training

\n======================================================================\ncyp2c19_val.csv: (27, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0  O=C1CN(S(=O)(=O)/C=C/c2ccc(Cl)s2)CCN1Cc1cc2cnc...    0.0   val
1                        Cc1cccc(Nc2ccccc2C(=O)O)c1C    0.0   val
2  CC(=O)C1CC[C@H]2[C@@H]3CC=C4CC(=O)CC[C@]4(C)[C...    1.0   val
3           COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1    1.0   val
4                    Cc1c(N(C)C)c(=O)n(-c2ccccc2)n1C    1.0   val

\n======================================================================\ncyp2c9_test.csv: (103, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0         CC(=O)C[C@@H](c1ccccc1)c1c(O)c2ccccc2oc1=O    1.0  test
1  COc1cc(N)c(Cl)cc1C(=O)N[C@@H]1CCN(CCCOc2ccc(F)...    1.0  test
2       Clc1ccc(CS[C@@H](Cn2ccnc2)c2ccc(Cl)cc2Cl)cc1    0.0  test
3        CCc1cccc2c3c([nH]c12)[C@@](CC)(CC(=O)O)OCC3    1.0  test
4                       CN(C)c1cn(C)n(-c2ccccc2)c1=O    1.0  test

\n======================================================================\ncyp2c9_train.csv: (827, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label     group
0                               C=CCc1ccc(OC)c(OC)c1    1.0  training
1               CC[C@]1(c2ccccc2)C(=O)NC(=O)N(C)C1=O    0.0  training
2  CC[C@@H]1[C@@H]2C[C@H]3[C@@H]4N(C)c5ccccc5[C@]...    0.0  training
3       O=C1C=C2CN(C(C(=O)C3CC3)c3ccccc3F)CC[C@H]2S1    1.0  training
4             CCN(CCO)CCC[C@H](C)Nc1ccnc2cc(Cl)ccc12    0.0  training

\n======================================================================\ncyp2c9_val.csv: (104, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0  Cc1ccc(C(=O)NCCc2ccc(S(=O)(=O)NC(=O)NC3CCCCC3)...    1.0   val
1                     C[C@@H]1O[C@@]2(CS1)CN1CCC2CC1    1.0   val
2  C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@@H](O)c1ccnc2cc...    1.0   val
3       CC(C)NC[C@@H]1CCc2cc(CO)c([N+](=O)[O-])cc2N1    0.0   val
4   COc1ccccc1OCCNC[C@@H](O)COc1cccc2[nH]c3ccccc3c12    1.0   val

\n======================================================================\ncyp2d6_test.csv: (92, 3)
Columns: ['smiles_standarized', 'label', 'group']

                  smiles_standarized  label group
0                 Oc1ccccc1-c1ccccc1    1.0  test
1                     NCCc1ccc(O)cc1    1.0  test
2  Nc1ccc([N+](=O)[O-])c(C(F)(F)F)c1    1.0  test
3             CN[C@@H](C)Cc1ccccc1OC    1.0  test
4   COc1cc(CNC(=O)CCCCC=CC(C)C)ccc1O    1.0  test

\n======================================================================\ncyp2d6_train.csv: (733, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label     group
0                           C[C@@H](Cc1ccccc1)NCCC#N    1.0  training
1                              NC[C@H](O)c1ccc(O)cc1    1.0  training
2                               C=CCc1ccc(OC)c(OC)c1    1.0  training
3  CC[C@H]1CN2CCc3cc(OC)c(OC)cc3[C@@H]2C[C@@H]1C[...    1.0  training
4                       CN[C@@H](C)[C@@H](O)c1ccccc1    1.0  training

\n======================================================================\ncyp2d6_val.csv: (92, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                 smiles_standarized  label group
0                                         CCN(C)N=O    1.0   val
1                    CN(C)CCC(c1ccc(Br)cc1)c1ccccn1    1.0   val
2                        N=C(N)NC[C@H]1COc2ccccc2O1    1.0   val
3                        CCOc1ccc2cc(C#N)c(=O)oc2c1    1.0   val
4  Cc1c(OCC(F)(F)F)ccnc1C[S+]([O-])c1nc2ccccc2[nH]1    0.0   val

\n======================================================================\ncyp3a4_test.csv: (155, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0  CC(O)(CS(=O)(=O)c1ccc(F)cc1)C(=O)Nc1ccc(C#N)c(...    1.0  test
1  CC[C@H](OC(C)=O)C(C[C@@H](C)N(C)C)(c1ccccc1)c1...    0.0  test
2                       COc1ccc2[nH]cc(CCC(=O)O)c2c1    0.0  test
3        CNC(=O)CN1CCC(Nc2nccc(-c3cnc4ccccn34)n2)CC1    0.0  test
4                  O=c1[nH]c(=O)n(COCCO)cc1Sc1ccccc1    0.0  test

\n======================================================================\ncyp3a4_train.csv: (1241, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label     group
0  CC1C(=O)N2CCC[C@H]2[C@]2(O)O[C@](NC(=O)C3C[C@@...    1.0  training
1  CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C/CC/C(C)=C...    0.0  training
2                            CCCCCCCCCCCCOS(=O)(=O)O    0.0  training
3                         O=c1cccc2n1C[C@@H]1CNCC2C1    0.0  training
4         NS(=O)(=O)c1ccc(C(=O)NCc2ccc(F)c(F)c2F)cc1    0.0  training

\n======================================================================\ncyp3a4_val.csv: (155, 3)
Columns: ['smiles_standarized', 'label', 'group']

                                  smiles_standarized  label group
0       O=C(O)c1ccc(-c2c[nH]c3ncc(-c4ccccc4)cc23)cc1    0.0   val
1                                  CNC(CC(C)C)C(=O)O    0.0   val
2  CC(=O)N[C@@H]1[C@@H](O)[C@@H](O[C@@H]2O[C@H](C...    0.0   val
3  N[C@H]1C[C@@H](N2CCn3c(nnc3C(F)(F)F)C2)CC[C@@H...    0.0   val
4  COC1C(=O)C(C)C[C@H](C)/C=C/C=C/C=C(\C)[C@@H](O...    1.0   val

In [4]:
rows = []
for filename, df in datasets.items():
    rows.append({
        "file": filename,
        "rows": len(df),
        "columns": len(df.columns),
        "duplicate_rows": int(df.duplicated().sum()),
        "columns_list": ", ".join(map(str, df.columns))
    })
display(pd.DataFrame(rows))

,file,rows,columns,duplicate_rows,columns_list
0,cyp1a2_test.csv,37,3,0,"smiles_standarized, label, group"
1,cyp1a2_train.csv,292,3,0,"smiles_standarized, label, group"
2,cyp1a2_val.csv,37,3,0,"smiles_standarized, label, group"
3,cyp2c19_test.csv,26,3,0,"smiles_standarized, label, group"
4,cyp2c19_train.csv,208,3,0,"smiles_standarized, label, group"
5,cyp2c19_val.csv,27,3,0,"smiles_standarized, label, group"
6,cyp2c9_test.csv,103,3,0,"smiles_standarized, label, group"
7,cyp2c9_train.csv,827,3,0,"smiles_standarized, label, group"
8,cyp2c9_val.csv,104,3,0,"smiles_standarized, label, group"
9,cyp2d6_test.csv,92,3,0,"smiles_standarized, label, group"
10,cyp2d6_train.csv,733,3,0,"smiles_standarized, label, group"
11,cyp2d6_val.csv,92,3,0,"smiles_standarized, label, group"
12,cyp3a4_test.csv,155,3,0,"smiles_standarized, label, group"
13,cyp3a4_train.csv,1241,3,0,"smiles_standarized, label, group"
14,cyp3a4_val.csv,155,3,0,"smiles_standarized, label, group"

In [5]:
candidates = {
    "SMILES": {"smiles", "canonical_smiles", "canonical smiles", "isomeric_smiles"},
    "label/activity": {"substrate_label", "label", "activity", "class", "substrate"},
    "compound ID": {"compound_id", "cid", "chembl_id", "id", "molecule_id"},
    "isoform": {"cyp_isoform", "isoform", "enzyme", "target"}
}
for filename, df in datasets.items():
    print("\\n", filename)
    for kind, terms in candidates.items():
        matches = [c for c in df.columns if str(c).strip().lower() in terms]
        print(kind, ":", matches or "not automatically identified")

\n cyp1a2_test.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp1a2_train.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp1a2_val.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2c19_test.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2c19_train.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2c19_val.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2c9_test.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2c9_train.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2c9_val.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2d6_test.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2d6_train.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp2d6_val.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp3a4_test.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp3a4_train.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified
\n cyp3a4_val.csv
SMILES : not automatically identified
label/activity : ['label']
compound ID : not automatically identified
isoform : not automatically identified

In [6]:
%pip install rdkit

Requirement already satisfied: rdkit in c:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (2026.9.1)
Requirement already satisfied: numpy in c:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (from rdkit) (2.5.4)
Requirement already satisfied: Pillow in c:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\.venv\Lib\site-packages (from rdkit) (12.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:

from pathlib import Path
import pandas as pd
from rdkit import Chem, rdBase

print("RDKit version:", rdBase.rdkitVersion)

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
RESULTS_DIR = PROJECT_ROOT / "results" / "metrics"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

validation_rows = []
invalid_rows = []

for file in sorted(RAW_DIR.glob("*.csv")):
    df = pd.read_csv(file)

    for idx, smiles in df["smiles_standarized"].items():
        mol = Chem.MolFromSmiles(str(smiles)) if pd.notna(smiles) else None

        validation_rows.append({
            "file": file.name,
            "row_index": idx,
            "valid_smiles": mol is not None
        })

        if mol is None:
            invalid_rows.append({
                "file": file.name,
                "row_index": idx,
                "smiles": smiles,
                "label": df.loc[idx, "label"]
            })

validation = pd.DataFrame(validation_rows)
invalid = pd.DataFrame(
    invalid_rows,
    columns=["file", "row_index", "smiles", "label"]
)

print("Total structures checked:", len(validation))
print("Valid structures:", int(validation["valid_smiles"].sum()))
print("Invalid structures:", int((~validation["valid_smiles"]).sum()))

print("\nValidity by file:")
display(
    validation.groupby("file")["valid_smiles"]
    .agg(["count", "sum"])
    .rename(columns={"count": "total", "sum": "valid"})
)

print("\nExamples of invalid structures:")
display(invalid.head(20))

validation.to_csv(
    RESULTS_DIR / "smiles_validation.csv", index=False
)
invalid.to_csv(
    RESULTS_DIR / "invalid_smiles_review.csv", index=False
)

print("\nAudit files saved to:", RESULTS_DIR)

RDKit version: 2026.09.1

[18:18:43] Explicit valence for atom # 10 N, 5, is greater than permitted
[18:18:44] Explicit valence for atom # 10 N, 5, is greater than permitted

Total structures checked: 4129
Valid structures: 4127
Invalid structures: 2

Validity by file:

                   total  valid
file
cyp1a2_test.csv       37     37
cyp1a2_train.csv     292    292
cyp1a2_val.csv        37     37
cyp2c19_test.csv      26     26
cyp2c19_train.csv    208    208
cyp2c19_val.csv       27     27
cyp2c9_test.csv      103    103
cyp2c9_train.csv     827    826
cyp2c9_val.csv       104    104
cyp2d6_test.csv       92     91
cyp2d6_train.csv     733    733
cyp2d6_val.csv        92     92
cyp3a4_test.csv      155    155
cyp3a4_train.csv    1241   1241
cyp3a4_val.csv       155    155

Examples of invalid structures:

,file,row_index,smiles,label
0,cyp2c9_train.csv,248,O=C(OC1C[C-]2CCC(C1)[N+2]21(Cl)[C-2]CC[C-2]1)C...,0.0
1,cyp2d6_test.csv,16,O=C(OC1C[C-]2CCC(C1)[N+2]21(Cl)[C-2]CC[C-2]1)C...,0.0

Audit files saved to: c:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\results\metrics

In [8]:

from pathlib import Path
import pandas as pd
from rdkit import Chem

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
RESULTS_DIR = PROJECT_ROOT / "results" / "metrics"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

valid_records = []
invalid_records = []

for file in sorted(RAW_DIR.glob("*.csv")):
    df = pd.read_csv(file)

    isoform, split = file.stem.rsplit("_", 1)

    for row_idx, row in df.iterrows():
        smiles = row["smiles_standarized"]
        mol = Chem.MolFromSmiles(str(smiles)) if pd.notna(smiles) else None

        record = {
            "source_file": file.name,
            "source_row_index": row_idx,
            "isoform": isoform.upper(),
            "split": split,
            "smiles_original": smiles,
            "label": row["label"],
            "group": row["group"]
        }

        if mol is None:
            invalid_records.append(record)
            continue

        record["smiles_canonical"] = Chem.MolToSmiles(
            mol, canonical=True
        )
        valid_records.append(record)

cleaned = pd.DataFrame(valid_records)
invalid = pd.DataFrame(invalid_records)

# Save the cleaned modeling dataset and the invalid records separately.
cleaned.to_csv(
    PROCESSED_DIR / "cyp_substrates_cleaned.csv",
    index=False
)
invalid.to_csv(
    RESULTS_DIR / "invalid_structures_for_review.csv",
    index=False
)

print("Original records:", len(valid_records) + len(invalid_records))
print("Valid records retained:", len(cleaned))
print("Invalid records set aside:", len(invalid))
print("Missing canonical SMILES:", cleaned["smiles_canonical"].isna().sum())

print("\nValid records per isoform and split:")
display(
    cleaned.groupby(["isoform", "split"])
    .size()
    .unstack(fill_value=0)
)

print("\nInvalid records — full SMILES:")
if len(invalid):
    with pd.option_context("display.max_colwidth", None):
        display(invalid[[
            "source_file", "source_row_index",
            "smiles_original", "label"
        ]])
else:
    print("No invalid records.")

print("\nSaved cleaned dataset to:")
print(PROCESSED_DIR / "cyp_substrates_cleaned.csv")

[18:18:45] Explicit valence for atom # 10 N, 5, is greater than permitted
[18:18:46] Explicit valence for atom # 10 N, 5, is greater than permitted

Original records: 4129
Valid records retained: 4127
Invalid records set aside: 2
Missing canonical SMILES: 0

Valid records per isoform and split:

split    test  train  val
isoform
CYP1A2     37    292   37
CYP2C19    26    208   27
CYP2C9    103    826  104
CYP2D6     91    733   92
CYP3A4    155   1241  155

Invalid records — full SMILES:

,source_file,source_row_index,smiles_original,label
0,cyp2c9_train.csv,248,O=C(OC1C[C-]2CCC(C1)[N+2]21(Cl)[C-2]CC[C-2]1)C(O)(c1ccccc1)c1ccccc1,0.0
1,cyp2d6_test.csv,16,O=C(OC1C[C-]2CCC(C1)[N+2]21(Cl)[C-2]CC[C-2]1)C(O)(c1ccccc1)c1ccccc1,0.0

Saved cleaned dataset to:
c:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\data\processed\cyp_substrates_cleaned.csv

In [9]:

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

CLEANED_FILE = (
    PROJECT_ROOT / "data" / "processed"
    / "cyp_substrates_cleaned.csv"
)
RESULTS_DIR = PROJECT_ROOT / "results" / "metrics"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(CLEANED_FILE)

# How many distinct compounds occur in each partition?
print("Distinct canonical compounds by isoform and partition:")
display(
    df.groupby(["isoform", "split"])["smiles_canonical"]
      .nunique()
      .unstack(fill_value=0)
)

# For each compound, record every partition in which it appears.
compound_partitions = (
    df.groupby("smiles_canonical")["split"]
      .agg(lambda values: sorted(set(values)))
      .reset_index(name="partitions")
)

compound_partitions["number_of_partitions"] = (
    compound_partitions["partitions"].str.len()
)

cross_partition_compounds = compound_partitions[
    compound_partitions["number_of_partitions"] > 1
].copy()

print(
    "\nDistinct compounds appearing in multiple partitions:",
    len(cross_partition_compounds)
)

display(cross_partition_compounds.head(20))

# Count compounds that appear in each pair of partitions.
partition_sets = {
    split: set(df.loc[df["split"] == split, "smiles_canonical"])
    for split in ["train", "val", "test"]
}

pairwise_overlap = []
for a, b in [
    ("train", "val"),
    ("train", "test"),
    ("val", "test")
]:
    shared = partition_sets[a] & partition_sets[b]
    pairwise_overlap.append({
        "partition_1": a,
        "partition_2": b,
        "shared_canonical_compounds": len(shared)
    })

print("\nGlobal partition overlap across all isoforms:")
display(pd.DataFrame(pairwise_overlap))

# Save the audit outputs.
cross_partition_compounds.to_csv(
    RESULTS_DIR / "cross_partition_compounds.csv",
    index=False
)

pd.DataFrame(pairwise_overlap).to_csv(
    RESULTS_DIR / "global_partition_overlap.csv",
    index=False
)

print("\nAudit outputs saved to:", RESULTS_DIR)

Distinct canonical compounds by isoform and partition:

split    test  train  val
isoform
CYP1A2     37    292   37
CYP2C19    26    208   27
CYP2C9    103    826  104
CYP2D6     91    733   92
CYP3A4    155   1241  155

Distinct compounds appearing in multiple partitions: 505

,smiles_canonical,partitions,number_of_partitions
1,C#CCN(C)C(C)Cc1ccccc1,"[test, train]",2
6,C#CC[C@]12CCC(=O)C=C1CC[C@@H]1[C@@H]2CC[C@]2(C...,"[train, val]",2
7,C#C[C@]1(O)C=C[C@H]2[C@@H]3CC=C4CC(=O)CCC4[C@H...,"[train, val]",2
9,C#C[C@]1(O)CC[C@H]2[C@@H]3CC=C4CC(=O)CCC4[C@H]...,"[test, train]",2
10,C#C[C@]1(O)CC[C@H]2[C@@H]3CC=C4CC(=O)CCC4[C@H]...,"[test, train]",2
11,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CCCC[C@@H]4[C@H...,"[test, train, val]",3
13,C#C[C@]1(O)CC[C@H]2[C@@H]3CCc4cc(O)ccc4[C@H]3C...,"[train, val]",2
14,C#C[C@]1(O)CC[C@H]2[C@@H]3CCc4cc(OC)ccc4[C@H]3...,"[train, val]",2
34,C=C(c1ccc(C(=O)O)cc1)c1cc2c(cc1C)C(C)(C)CCC2(C)C,"[test, train]",2
51,C=CCC1([C@@H](C)CCC)C(=O)NC(=O)NC1=O,"[train, val]",2
63,C=CCSSCC=C,"[test, val]",2
66,C=CCc1c(O)n2c(N(C)C)nc3ccc(C)cc3n2c1=O,"[train, val]",2
69,C=CCc1ccc2c(c1)OCO2,"[train, val]",2
72,C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@@H](O)c1ccnc2cc...,"[train, val]",2
73,C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@H](O)c1ccnc2ccc...,"[train, val]",2
74,C=C[C@H]1CN2CC[C@H]1C[C@H]2[C@H](O)c1ccnc2ccc(...,"[train, val]",2
80,CC#C[C@]1(O)CC[C@H]2C3=C(C4=C(CC3)CC(=O)CC4)C(...,"[train, val]",2
83,CC(=O)C1CC[C@@H]2[C@H]3CC=C4CC(=O)CC[C@@]4(C)[...,"[test, train]",2
85,CC(=O)C1CC[C@H]2[C@@H]3CC=C4CC(=O)CC[C@]4(C)[C...,"[test, train, val]",3
87,CC(=O)C1CC[C@H]2[C@@H]3CC[C@H]4C[C@](C)(O)CC[C...,"[train, val]",2

Global partition overlap across all isoforms:

  partition_1 partition_2  shared_canonical_compounds
0       train         val                         267
1       train        test                         272
2         val        test                          52

Audit outputs saved to: c:\Users\PAWAR ARAVIND\OneDrive\Desktop\CYP450_Substrate_Liability\results\metrics

In [10]:

from itertools import combinations
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

df = pd.read_csv(
    PROJECT_ROOT / "data" / "processed" / "cyp_substrates_cleaned.csv"
)

# For each canonical compound, list every isoform/partition combination.
compound_locations = (
    df.groupby("smiles_canonical")
      .apply(
          lambda g: sorted(set(
              zip(g["isoform"], g["split"])
          )),
          include_groups=False
      )
      .rename("locations")
      .reset_index()
)

# Count cross-partition sharing between different CYP isoforms.
records = []

for _, row in compound_locations.iterrows():
    locations = row["locations"]

    for loc1, loc2 in combinations(locations, 2):
        iso1, split1 = loc1
        iso2, split2 = loc2

        if iso1 != iso2 and split1 != split2:
            records.append({
                "isoform_1": iso1,
                "split_1": split1,
                "isoform_2": iso2,
                "split_2": split2,
                "smiles_canonical": row["smiles_canonical"]
            })

cross_isoform_leakage = pd.DataFrame(records)

if len(cross_isoform_leakage):
    summary = (
        cross_isoform_leakage
        .groupby([
            "isoform_1", "split_1",
            "isoform_2", "split_2"
        ])["smiles_canonical"]
        .nunique()
        .reset_index(name="shared_compounds")
        .sort_values("shared_compounds", ascending=False)
    )
    display(summary)
else:
    print("No cross-isoform cross-partition overlaps detected.")

out_dir = PROJECT_ROOT / "results" / "metrics"
out_dir.mkdir(parents=True, exist_ok=True)

cross_isoform_leakage.to_csv(
    out_dir / "cross_isoform_partition_overlap_details.csv",
    index=False
)

print("Detailed overlap records:", len(cross_isoform_leakage))

   isoform_1 split_1 isoform_2 split_2  shared_compounds
49    CYP2C9     val    CYP3A4   train                79
44    CYP2C9   train    CYP3A4    test                78
45    CYP2C9   train    CYP3A4     val                69
40    CYP2C9    test    CYP3A4   train                69
47    CYP2C9     val    CYP2D6   train                64
38    CYP2C9    test    CYP2D6   train                62
42    CYP2C9   train    CYP2D6    test                62
52    CYP2D6   train    CYP3A4    test                60
55    CYP2D6     val    CYP3A4   train                58
43    CYP2C9   train    CYP2D6     val                57
50    CYP2D6    test    CYP3A4   train                53
53    CYP2D6   train    CYP3A4     val                51
20    CYP1A2     val    CYP3A4   train                18
12    CYP1A2   train    CYP3A4    test                14
9     CYP1A2   train    CYP2C9     val                13
32   CYP2C19   train    CYP3A4     val                13
10    CYP1A2   train    CYP2D6    test                13
13    CYP1A2   train    CYP3A4     val                13
37   CYP2C19     val    CYP3A4   train                12
8     CYP1A2   train    CYP2C9    test                12
17    CYP1A2     val    CYP2C9   train                12
39    CYP2C9    test    CYP2D6     val                11
25   CYP2C19    test    CYP3A4   train                11
19    CYP1A2     val    CYP2D6   train                11
35   CYP2C19     val    CYP2D6   train                10
21   CYP2C19    test    CYP2C9   train                10
2     CYP1A2    test    CYP2C9   train                 9
4     CYP1A2    test    CYP3A4   train                 9
54    CYP2D6     val    CYP3A4    test                 8
29   CYP2C19   train    CYP2D6    test                 8
28   CYP2C19   train    CYP2C9     val                 8
48    CYP2C9     val    CYP3A4    test                 8
3     CYP1A2    test    CYP2D6   train                 8
34   CYP2C19     val    CYP2C9   train                 8
51    CYP2D6    test    CYP3A4     val                 7
11    CYP1A2   train    CYP2D6     val                 7
46    CYP2C9     val    CYP2D6    test                 7
7     CYP1A2   train   CYP2C19     val                 5
0     CYP1A2    test   CYP2C19   train                 5
6     CYP1A2   train   CYP2C19    test                 5
31   CYP2C19   train    CYP3A4    test                 5
27   CYP2C19   train    CYP2C9    test                 5
24   CYP2C19    test    CYP2D6     val                 5
30   CYP2C19   train    CYP2D6     val                 4
41    CYP2C9    test    CYP3A4     val                 4
23   CYP2C19    test    CYP2D6   train                 4
36   CYP2C19     val    CYP3A4    test                 3
1     CYP1A2    test   CYP2C19     val                 1
22   CYP2C19    test    CYP2C9     val                 1
18    CYP1A2     val    CYP2D6    test                 1
16    CYP1A2     val    CYP2C9    test                 1
15    CYP1A2     val   CYP2C19   train                 1
14    CYP1A2     val   CYP2C19    test                 1
5     CYP1A2    test    CYP3A4     val                 1
33   CYP2C19     val    CYP2C9    test                 1
26   CYP2C19    test    CYP3A4     val                 1

Detailed overlap records: 1076